# --- Court-to-State mapping for India Map ---
COURT_STATE_MAP = {
    "supreme court of india": "Delhi",
    "supreme court": "Delhi",
    "high court - delhi": "Delhi",
    "delhi high court": "Delhi",
    "high court - bombay": "Maharashtra",
    "bombay high court": "Maharashtra",
    "high court - madras": "Tamil Nadu",
    "madras high court": "Tamil Nadu",
    "high court - calcutta": "West Bengal",
    "calcutta high court": "West Bengal",
    "high court - karnataka": "Karnataka",
    "karnataka high court": "Karnataka",
    "high court - kerala": "Kerala",
    "kerala high court": "Kerala",
    "high court - allahabad": "Uttar Pradesh",
    "allahabad high court": "Uttar Pradesh",
    "high court - patna": "Bihar",
    "patna high court": "Bihar",
    "high court - rajasthan": "Rajasthan",
    "rajasthan high court": "Rajasthan",
    "high court - gujarat": "Gujarat",
    "gujarat high court": "Gujarat",
    "high court - punjab and haryana": "Punjab",
    "punjab and haryana high court": "Punjab",
    "high court - hyderabad": "Telangana",
    "telangana high court": "Telangana",
    "high court - andhra pradesh": "Andhra Pradesh",
    "andhra pradesh high court": "Andhra Pradesh",
    "high court - orissa": "Odisha",
    "orissa high court": "Odisha",
    "high court - gauhati": "Assam",
    "gauhati high court": "Assam",
    "high court - madhya pradesh": "Madhya Pradesh",
    "madhya pradesh high court": "Madhya Pradesh",
    "high court - jharkhand": "Jharkhand",
    "jharkhand high court": "Jharkhand",
    "high court - chhattisgarh": "Chhattisgarh",
    "chhattisgarh high court": "Chhattisgarh",
    "high court - uttarakhand": "Uttarakhand",
    "uttarakhand high court": "Uttarakhand",
    "high court - himachal pradesh": "Himachal Pradesh",
    "high court - goa": "Goa",
    "high court - manipur": "Manipur",
    "high court - meghalaya": "Meghalaya",
    "high court - tripura": "Tripura",
    "high court - sikkim": "Sikkim",
    "new delhi": "Delhi",
    "mumbai": "Maharashtra",
    "chennai": "Tamil Nadu",
    "kolkata": "West Bengal",
    "bangalore": "Karnataka",
    "bengaluru": "Karnataka",
    "hyderabad": "Telangana",
    "ahmedabad": "Gujarat",
    "pune": "Maharashtra",
    "lucknow": "Uttar Pradesh",
    "jaipur": "Rajasthan",
    "chandigarh": "Punjab",
    "kochi": "Kerala",
    "bhopal": "Madhya Pradesh",
    "patna": "Bihar",
    "guwahati": "Assam",
}