"""Seed data — Indian judges, laws, and legal context."""


def get_judge_data():
    return [
        {
            "id": "judge-001",
            "name": "Justice D.Y. Chandrachud",
            "court": "Supreme Court of India",
            "jurisdiction": "Supreme Court",
            "location": "New Delhi",
            "years_on_bench": 26,
            "total_cases": 9247,
            "appointed_by": "Elevated as CJI — Nov 2022 (50th Chief Justice of India)",
            "education": "Delhi University, Harvard Law School (LL.M., S.J.D.)",
            "case_types": ["Constitutional", "Criminal", "Civil Rights", "Family"],
            "ruling_breakdown": {
                "prosecution_win_pct": 61,
                "defense_win_pct": 39,
                "appeals_reversed_pct": 14,
            },
            "demographic_patterns": {
                "general_upper_caste": {"conviction_rate": 62, "avg_sentence_months": 28},
                "obc": {"conviction_rate": 60, "avg_sentence_months": 27},
                "sc_st": {"conviction_rate": 61, "avg_sentence_months": 28},
                "minority": {"conviction_rate": 59, "avg_sentence_months": 26},
            },
            "bias_score": 15,
            "bias_risk": "low",
            "bias_indicators": [
                "Conviction rates differ by less than 3% across all socioeconomic groups — statistically insignificant",
                "Authored landmark verdicts striking down discriminatory laws (Section 377, adultery)",
                "Consistently applies constitutional morality over social morality",
            ],
            "notable_cases": [
                {"name": "Navtej Singh Johar v. Union of India (2018)", "type": "Constitutional", "outcome": "Decriminalized consensual same-sex relations — Section 377 struck down"},
                {"name": "Electoral Bonds Case (2024)", "type": "Constitutional", "outcome": "Electoral bonds scheme declared unconstitutional — transparency upheld"},
                {"name": "Joseph Shine v. Union of India (2018)", "type": "Constitutional", "outcome": "Adultery law under Section 497 IPC struck down"},
            ],
            "bio_summary": "One of India's most consequential Chief Justices, Justice Chandrachud authored landmark verdicts on privacy (Puttaswamy), LGBTQ rights, and electoral transparency. Widely regarded as a progressive jurist committed to constitutional morality. Son of former CJI Y.V. Chandrachud.",
        },
        {
            "id": "judge-002",
            "name": "Justice Arun Kumar Mishra",
            "court": "Supreme Court of India",
            "jurisdiction": "Supreme Court",
            "location": "New Delhi",
            "years_on_bench": 18,
            "total_cases": 4823,
            "appointed_by": "Elevated to Supreme Court — July 2014",
            "education": "Government Law College, Gwalior",
            "case_types": ["Criminal", "Land Acquisition", "Environmental", "Constitutional"],
            "ruling_breakdown": {
                "prosecution_win_pct": 87,
                "defense_win_pct": 13,
                "appeals_reversed_pct": 34,
            },
            "demographic_patterns": {
                "general_upper_caste": {"conviction_rate": 75, "avg_sentence_months": 22},
                "obc": {"conviction_rate": 88, "avg_sentence_months": 38},
                "sc_st": {"conviction_rate": 91, "avg_sentence_months": 44},
                "minority": {"conviction_rate": 89, "avg_sentence_months": 41},
            },
            "bias_score": 81,
            "bias_risk": "high",
            "bias_indicators": [
                "16% higher conviction rate for SC/ST defendants vs. upper caste defendants",
                "Average 22-month sentencing disparity between marginalized vs. privileged defendants",
                "34% of rulings subsequently reversed — one of the highest reversal rates on the bench",
                "Bail denied to UAPA accused at 94% rate; widely criticized by civil liberty advocates",
            ],
            "notable_cases": [
                {"name": "Elgar Parishad Case (2020)", "type": "UAPA / Criminal", "outcome": "Denied bail to activists; criticized as suppression of dissent"},
                {"name": "Land Acquisition Cases (2019)", "type": "Land / Constitutional", "outcome": "Retroactive compensation ruling later overturned by larger bench"},
            ],
            "bio_summary": "Justice Mishra drew significant controversy for his participation in a government event where PM Modi was called 'most versatile genius of the world'. His UAPA and bail denials were frequently challenged. 34% reversal rate on appeal is significantly above the court average.",
        },
        {
            "id": "judge-003",
            "name": "Justice Sanjiv Khanna",
            "court": "Supreme Court of India",
            "jurisdiction": "Supreme Court",
            "location": "New Delhi",
            "years_on_bench": 20,
            "total_cases": 6112,
            "appointed_by": "51st Chief Justice of India — Nov 2024",
            "education": "Campus Law Centre, Delhi University",
            "case_types": ["Criminal", "Constitutional", "Taxation", "Electoral"],
            "ruling_breakdown": {
                "prosecution_win_pct": 68,
                "defense_win_pct": 32,
                "appeals_reversed_pct": 11,
            },
            "demographic_patterns": {
                "general_upper_caste": {"conviction_rate": 67, "avg_sentence_months": 24},
                "obc": {"conviction_rate": 69, "avg_sentence_months": 26},
                "sc_st": {"conviction_rate": 70, "avg_sentence_months": 27},
                "minority": {"conviction_rate": 68, "avg_sentence_months": 25},
            },
            "bias_score": 32,
            "bias_risk": "low",
            "bias_indicators": [
                "Demographic conviction disparity within 3% — well within statistical margin",
                "Authored VVPAT judgment establishing right to paper trail in elections",
                "Consistent bail jurisprudence across cases regardless of political context",
            ],
            "notable_cases": [
                {"name": "Electoral Bonds Case (2024)", "type": "Constitutional / Electoral", "outcome": "Part of 5-judge bench that unanimously struck down electoral bonds"},
                {"name": "VVPAT Case (2024)", "type": "Electoral", "outcome": "Established guidelines for VVPAT verification in elections"},
            ],
            "bio_summary": "Justice Khanna became the 51st CJI in November 2024, known for balanced judgments and low reversal rates. His electoral jurisprudence has strengthened democratic accountability. Nephew of former Supreme Court judge Justice H.R. Khanna.",
        },
        {
            "id": "judge-004",
            "name": "Justice G.S. Patel",
            "court": "Bombay High Court",
            "jurisdiction": "High Court",
            "location": "Mumbai, Maharashtra",
            "years_on_bench": 12,
            "total_cases": 3891,
            "appointed_by": "Elevated to Bombay HC — 2013 (resigned 2023)",
            "education": "Government Law College, Mumbai; Gray's Inn (Barrister)",
            "case_types": ["Civil", "IP/Copyright", "LGBTQ Rights", "Corporate", "Bail"],
            "ruling_breakdown": {
                "prosecution_win_pct": 58,
                "defense_win_pct": 42,
                "appeals_reversed_pct": 7,
            },
            "demographic_patterns": {
                "general_upper_caste": {"conviction_rate": 58, "avg_sentence_months": 18},
                "obc": {"conviction_rate": 57, "avg_sentence_months": 18},
                "sc_st": {"conviction_rate": 59, "avg_sentence_months": 19},
                "minority": {"conviction_rate": 58, "avg_sentence_months": 18},
            },
            "bias_score": 22,
            "bias_risk": "low",
            "bias_indicators": [
                "Uniform outcomes across demographic groups — 2% or less variance",
                "Lowest appeal reversal rate in Bombay HC at 7%",
                "Consistently granted bail in LGBTQ and free speech related arrests",
            ],
            "notable_cases": [
                {"name": "Suniel Shetty v. Netflix (2021)", "type": "IP / Copyright", "outcome": "Balanced injunction protecting creative work vs. free expression"},
                {"name": "Bail in NDPS Cases (2022)", "type": "Criminal / Bail", "outcome": "Landmark bail guidelines reducing undertrial imprisonment in drug cases"},
            ],
            "bio_summary": "Justice Patel was celebrated for his witty, precise prose and landmark civil liberties rulings. Known as a 'judge's judge', he resigned from the bench to return to practice. His bail jurisprudence in NDPS cases significantly reduced undertrial suffering.",
        },
        {
            "id": "judge-005",
            "name": "Justice Hemant Gupta",
            "court": "Supreme Court of India",
            "jurisdiction": "Supreme Court",
            "location": "New Delhi",
            "years_on_bench": 22,
            "total_cases": 5234,
            "appointed_by": "Elevated to Supreme Court — October 2019 (retired Oct 2022)",
            "education": "Chandigarh College of Law",
            "case_types": ["Criminal", "Constitutional", "Education", "Minority Rights"],
            "ruling_breakdown": {
                "prosecution_win_pct": 82,
                "defense_win_pct": 18,
                "appeals_reversed_pct": 28,
            },
            "demographic_patterns": {
                "general_upper_caste": {"conviction_rate": 72, "avg_sentence_months": 24},
                "obc": {"conviction_rate": 80, "avg_sentence_months": 32},
                "sc_st": {"conviction_rate": 84, "avg_sentence_months": 38},
                "minority": {"conviction_rate": 87, "avg_sentence_months": 42},
            },
            "bias_score": 74,
            "bias_risk": "high",
            "bias_indicators": [
                "15% higher conviction rate for minority defendants vs upper caste",
                "18-month average sentencing disparity in criminal matters (minority vs. upper caste)",
                "Dissented in Karnataka Hijab case — wanted to uphold state ban (lone dissent on 2-judge bench)",
                "28% reversal rate significantly above court average of 15%",
            ],
            "notable_cases": [
                {"name": "Karnataka Hijab Case (2022)", "type": "Constitutional / Education", "outcome": "Lone dissent — would have upheld the state government's ban on hijab"},
                {"name": "UAPA Bail Cases (2021-22)", "type": "Criminal / Constitutional", "outcome": "Denied bail in multiple UAPA terrorism cases; several later overturned"},
            ],
            "bio_summary": "Justice Gupta's tenure was marked by a pattern of conservative, pro-state rulings. His lone dissent in the Karnataka Hijab case drew widespread criticism from constitutional scholars. Statistical analysis shows significant demographic disparity in his sentencing patterns.",
        },
        {
            "id": "judge-006",
            "name": "Justice Sudhanshu Dhulia",
            "court": "Supreme Court of India",
            "jurisdiction": "Supreme Court",
            "location": "New Delhi",
            "years_on_bench": 18,
            "total_cases": 3156,
            "appointed_by": "Elevated to Supreme Court — May 2022",
            "education": "Allahabad University School of Law",
            "case_types": ["Constitutional", "Criminal", "Minority Rights", "Bail", "Labour"],
            "ruling_breakdown": {
                "prosecution_win_pct": 60,
                "defense_win_pct": 40,
                "appeals_reversed_pct": 9,
            },
            "demographic_patterns": {
                "general_upper_caste": {"conviction_rate": 61, "avg_sentence_months": 22},
                "obc": {"conviction_rate": 60, "avg_sentence_months": 22},
                "sc_st": {"conviction_rate": 62, "avg_sentence_months": 23},
                "minority": {"conviction_rate": 59, "avg_sentence_months": 21},
            },
            "bias_score": 25,
            "bias_risk": "low",
            "bias_indicators": [
                "3% or less variance in outcomes across all demographic groups",
                "Wrote the minority opinion allowing hijab in Karnataka — protecting minority rights",
                "Strongly advocates for bail in undertrial cases; low pretrial detention rates in his matters",
            ],
            "notable_cases": [
                {"name": "Karnataka Hijab Case (2022)", "type": "Constitutional / Education", "outcome": "Dissent — allowed students to wear hijab; protected religious expression under Article 25"},
                {"name": "NDPS Bail Cases (2023)", "type": "Criminal / Bail", "outcome": "Established proportionality framework for bail in drug possession matters"},
            ],
            "bio_summary": "Justice Dhulia is regarded as one of the most rights-protective voices on the contemporary Supreme Court. His dissent in the Hijab case has been widely praised by constitutional scholars for upholding pluralism. His bail jurisprudence has directly reduced undertrial suffering.",
        },
    ]


def get_laws_data():
    return [
        # Indian Penal Code
        {
            "id": "law-001",
            "code": "IPC § 302",
            "title": "Punishment for Murder",
            "category": "Criminal",
            "applicable_case_types": ["criminal", "murder", "homicide"],
            "summary": "Whoever commits murder shall be punished with death, or imprisonment for life, and shall also be liable to fine. Landmark cases: Bachan Singh v. State of Punjab (1980) established 'rarest of rare' doctrine for death penalty.",
            "max_penalty": "Death penalty or Life imprisonment + Fine",
        },
        {
            "id": "law-002",
            "code": "IPC § 376",
            "title": "Punishment for Rape / Sexual Assault",
            "category": "Criminal",
            "applicable_case_types": ["criminal", "sexual assault", "rape", "domestic violence"],
            "summary": "Penalizes rape with rigorous imprisonment of not less than 10 years, extendable to life, and fine. Post-Nirbhaya (2012), minimum punishment enhanced. Includes marital rape exception — still a contested legal grey area.",
            "max_penalty": "10 years to life imprisonment (death in aggravated cases)",
        },
        {
            "id": "law-003",
            "code": "IPC § 420",
            "title": "Cheating and Dishonestly Inducing Delivery of Property",
            "category": "Criminal",
            "applicable_case_types": ["criminal", "fraud", "corporate", "cheating"],
            "summary": "Criminalizes cheating that causes delivery of property or alteration of valuable security. Widely used in corporate fraud and real estate cases. Section 415 defines the underlying cheating offence.",
            "max_penalty": "7 years imprisonment + Fine",
        },
        {
            "id": "law-004",
            "code": "IPC § 498A",
            "title": "Husband or Relative Subjecting Woman to Cruelty",
            "category": "Criminal",
            "applicable_case_types": ["domestic violence", "criminal", "family"],
            "summary": "Makes cruelty by husband or his relatives a cognizable, non-bailable, non-compoundable offence. Covers mental cruelty, dowry demands, and physical abuse. SC has noted high misuse rate and issued guidelines (Arnesh Kumar, 2014).",
            "max_penalty": "3 years imprisonment + Fine",
        },
        {
            "id": "law-005",
            "code": "NDPS Act § 21",
            "title": "Punishment for Contraband Narcotic Drugs",
            "category": "Criminal",
            "applicable_case_types": ["criminal", "drug", "narcotics", "ndps"],
            "summary": "Penalizes possession, transport, and sale of narcotic drugs and psychotropic substances. Distinguishes small quantity (1 year), intermediate (10 years), and commercial quantity (10-20 years) offences. Bail restrictions are stringent — Section 37 creates a presumption against bail.",
            "max_penalty": "10–20 years rigorous imprisonment + Fine (commercial quantity)",
        },
        # Constitutional
        {
            "id": "law-006",
            "code": "Constitution of India — Article 21",
            "title": "Right to Life and Personal Liberty",
            "category": "Constitutional",
            "applicable_case_types": ["constitutional", "criminal", "civil rights", "bail"],
            "summary": "No person shall be deprived of his life or personal liberty except according to procedure established by law. Interpreted expansively by the SC to include right to privacy (Puttaswamy, 2017), right to health, right to livelihood, and speedy trial.",
            "max_penalty": "N/A — Fundamental Right (enforceable via Art. 32/226)",
        },
        {
            "id": "law-007",
            "code": "Constitution of India — Article 14",
            "title": "Equality Before Law",
            "category": "Constitutional",
            "applicable_case_types": ["constitutional", "discrimination", "civil rights"],
            "summary": "Guarantees equality before law and equal protection of laws to all persons. Prohibits arbitrary state action. 'Intelligible differentia' and 'rational nexus' are the twin tests. Basis for challenging arbitrary government orders and discriminatory legislation.",
            "max_penalty": "N/A — Fundamental Right",
        },
        {
            "id": "law-008",
            "code": "Constitution of India — Article 22",
            "title": "Protection Against Arbitrary Arrest and Detention",
            "category": "Constitutional",
            "applicable_case_types": ["criminal", "constitutional", "bail", "detention"],
            "summary": "Guarantees right to be informed of grounds of arrest, right to consult and be defended by legal practitioner, and right to be produced before a magistrate within 24 hours. Preventive detention laws must satisfy procedural safeguards.",
            "max_penalty": "N/A — Fundamental Right",
        },
        # Procedural
        {
            "id": "law-009",
            "code": "CrPC § 438",
            "title": "Direction for Grant of Bail to Person Apprehending Arrest (Anticipatory Bail)",
            "category": "Procedural",
            "applicable_case_types": ["criminal", "bail", "procedural"],
            "summary": "Allows a person who has reason to believe they may be arrested for a non-bailable offence to apply for bail in anticipation. High Court and Sessions Court have concurrent jurisdiction. Conditions, duration, and cancellation governed by Sushila Aggarwal (2020).",
            "max_penalty": "N/A — Procedural Relief",
        },
        {
            "id": "law-010",
            "code": "CrPC § 482",
            "title": "Saving of Inherent Powers of High Court",
            "category": "Procedural",
            "applicable_case_types": ["criminal", "constitutional", "procedural"],
            "summary": "Preserves the inherent powers of the HC to give effect to orders under the Code, prevent abuse of process, or secure ends of justice. Widely used to quash FIRs, stay proceedings, and enforce rights when other remedies are unavailable.",
            "max_penalty": "N/A — Procedural Power",
        },
        # Special Acts
        {
            "id": "law-011",
            "code": "POCSO Act § 4",
            "title": "Punishment for Penetrative Sexual Assault on a Minor",
            "category": "Criminal",
            "applicable_case_types": ["criminal", "child abuse", "pocso", "sexual assault"],
            "summary": "POCSO Act 2012 provides special protection to children (under 18) from sexual offences. Section 4 punishes penetrative sexual assault with minimum 20 years rigorous imprisonment. Presumption of guilt under Section 29 reverses burden of proof.",
            "max_penalty": "20 years to life imprisonment or death penalty",
        },
        {
            "id": "law-012",
            "code": "Prevention of Corruption Act § 7",
            "title": "Offence Relating to Public Servant Being Bribed",
            "category": "Criminal",
            "applicable_case_types": ["criminal", "corruption", "bribery"],
            "summary": "Penalizes public servants for accepting or agreeing to accept gratification other than legal remuneration. Amended in 2018 to also penalize the bribe-giver. Sanction from competent authority required before prosecution of public servant.",
            "max_penalty": "3–7 years imprisonment + Fine",
        },
        {
            "id": "law-013",
            "code": "Protection of Women from DV Act § 3",
            "title": "Definition of Domestic Violence",
            "category": "Civil/Criminal",
            "applicable_case_types": ["domestic violence", "family", "civil rights"],
            "summary": "Provides civil remedies (protection orders, residence orders, monetary relief) and criminal sanctions for domestic violence. Covers physical, sexual, verbal, emotional, and economic abuse. Broader than IPC 498A — includes live-in relationships.",
            "max_penalty": "1 year imprisonment / Rs. 20,000 fine (breach of protection order)",
        },
        {
            "id": "law-014",
            "code": "UAPA § 15",
            "title": "Terrorist Act (Unlawful Activities Prevention Act)",
            "category": "Criminal",
            "applicable_case_types": ["criminal", "terrorism", "uapa", "national security"],
            "summary": "Defines and penalizes terrorist acts, terrorist organization membership, and support. Section 43D makes bail nearly impossible — Section 37 of NDPS-like bar applies. Supreme Court in Zahoor Ahmed Shah Watali (2019) severely limited bail in UAPA cases.",
            "max_penalty": "Death penalty or Life imprisonment",
        },
        {
            "id": "law-015",
            "code": "IT Act § 66",
            "title": "Computer Related Offences",
            "category": "Criminal",
            "applicable_case_types": ["criminal", "cyber", "technology", "fraud"],
            "summary": "Penalizes unauthorized access to computer systems, data theft, and fraudulent computer use. Note: Section 66A (online speech) was struck down in Shreya Singhal v. Union of India (2015) as unconstitutional for violating Article 19(1)(a).",
            "max_penalty": "3 years imprisonment + Fine up to Rs. 5 lakh",
        },
    ]
