"""Seed data for Legal Intelligence System — judges, laws, sample cases."""


def get_judge_data():
    return [
        {
            "id": "judge-001",
            "name": "Hon. Margaret Chen",
            "court": "U.S. District Court, N.D. California",
            "jurisdiction": "Federal",
            "location": "San Francisco, CA",
            "years_on_bench": 15,
            "total_cases": 3247,
            "appointed_by": "Obama Administration (2010)",
            "education": "Harvard Law School",
            "case_types": ["Criminal", "Civil Rights", "Immigration"],
            "ruling_breakdown": {
                "prosecution_win_pct": 83,
                "defense_win_pct": 17,
                "appeals_reversed_pct": 22,
            },
            "demographic_patterns": {
                "white": {"conviction_rate": 78, "avg_sentence_months": 24},
                "black": {"conviction_rate": 89, "avg_sentence_months": 31},
                "hispanic": {"conviction_rate": 85, "avg_sentence_months": 28},
                "asian": {"conviction_rate": 75, "avg_sentence_months": 22},
            },
            "bias_score": 62,
            "bias_risk": "medium",
            "bias_indicators": [
                "12% higher conviction rate for Black defendants vs. white defendants",
                "7-month average sentencing disparity (Black vs. white defendants)",
                "Drug possession: consistently 15% above federal guidelines for minority defendants",
            ],
            "notable_cases": [
                {"name": "US v. Rivera (2022)", "type": "Drug Trafficking", "outcome": "32 months (above guidelines)"},
                {"name": "US v. Thompson (2021)", "type": "Financial Fraud", "outcome": "18 months (below guidelines)"},
            ],
            "bio_summary": "Appointed in 2010, Judge Chen is known for efficiency but has drawn scrutiny for sentencing disparities in drug-related cases.",
        },
        {
            "id": "judge-002",
            "name": "Hon. Robert Harrison",
            "court": "New York Supreme Court, Criminal Term",
            "jurisdiction": "State",
            "location": "New York, NY",
            "years_on_bench": 22,
            "total_cases": 5891,
            "appointed_by": "Elected (2003)",
            "education": "Columbia Law School",
            "case_types": ["Criminal", "Corporate", "Civil"],
            "ruling_breakdown": {
                "prosecution_win_pct": 91,
                "defense_win_pct": 9,
                "appeals_reversed_pct": 31,
            },
            "demographic_patterns": {
                "white": {"conviction_rate": 81, "avg_sentence_months": 18},
                "black": {"conviction_rate": 95, "avg_sentence_months": 36},
                "hispanic": {"conviction_rate": 93, "avg_sentence_months": 32},
                "asian": {"conviction_rate": 80, "avg_sentence_months": 19},
            },
            "bias_score": 84,
            "bias_risk": "high",
            "bias_indicators": [
                "14% higher conviction rate for minority defendants",
                "Bail denied for minority defendants 82% vs. 61% for white defendants",
                "Colloquially known as 'Maximum Harrison' for harsh sentencing",
                "31% of rulings reversed on appeal — above state average of 18%",
            ],
            "notable_cases": [
                {"name": "People v. Davis (2020)", "type": "Robbery", "outcome": "15 years — 3x minimum"},
                {"name": "Citigroup v. State (2019)", "type": "Corporate Fraud", "outcome": "Case dismissed on procedural grounds"},
            ],
            "bio_summary": "Judge Harrison has earned a reputation for maximum sentencing. His rulings have been scrutinized for racial disparities, with a high appeal reversal rate.",
        },
        {
            "id": "judge-003",
            "name": "Hon. Maria Santos",
            "court": "229th Criminal District Court, Texas",
            "jurisdiction": "State",
            "location": "Dallas, TX",
            "years_on_bench": 8,
            "total_cases": 1543,
            "appointed_by": "Elected (2017)",
            "education": "University of Texas School of Law",
            "case_types": ["Criminal", "Drug", "Juvenile"],
            "ruling_breakdown": {
                "prosecution_win_pct": 67,
                "defense_win_pct": 33,
                "appeals_reversed_pct": 8,
            },
            "demographic_patterns": {
                "white": {"conviction_rate": 65, "avg_sentence_months": 14},
                "black": {"conviction_rate": 69, "avg_sentence_months": 16},
                "hispanic": {"conviction_rate": 67, "avg_sentence_months": 15},
                "asian": {"conviction_rate": 64, "avg_sentence_months": 13},
            },
            "bias_score": 18,
            "bias_risk": "low",
            "bias_indicators": [
                "Sentencing disparities well within acceptable statistical variation",
                "34% higher use of diversion programs vs. state average",
                "Lowest appeal reversal rate in district at 8%",
            ],
            "notable_cases": [
                {"name": "State v. Morales (2023)", "type": "Drug Possession", "outcome": "Diversion program + treatment"},
                {"name": "State v. Williams (2022)", "type": "Assault", "outcome": "Probation + community service"},
            ],
            "bio_summary": "Judge Santos is known for progressive sentencing, emphasizing rehabilitation over incarceration. One of the most equitable records in the state.",
        },
        {
            "id": "judge-004",
            "name": "Hon. William Pierce",
            "court": "Ohio Court of Appeals, 10th District",
            "jurisdiction": "State Appeals",
            "location": "Columbus, OH",
            "years_on_bench": 30,
            "total_cases": 8024,
            "appointed_by": "Appointed (1995)",
            "education": "Ohio State Moritz College of Law",
            "case_types": ["Criminal Appeals", "Constitutional", "Civil Rights"],
            "ruling_breakdown": {
                "prosecution_win_pct": 79,
                "defense_win_pct": 21,
                "appeals_reversed_pct": 11,
            },
            "demographic_patterns": {
                "white": {"conviction_rate": 76, "avg_sentence_months": 20},
                "black": {"conviction_rate": 83, "avg_sentence_months": 27},
                "hispanic": {"conviction_rate": 80, "avg_sentence_months": 24},
                "asian": {"conviction_rate": 74, "avg_sentence_months": 19},
            },
            "bias_score": 55,
            "bias_risk": "medium",
            "bias_indicators": [
                "4th Amendment: rules for prosecution 76% of the time (national avg 58%)",
                "Conservative interpretation restricts exclusionary rule application",
                "7-month sentencing disparity for Black vs. white defendants",
            ],
            "notable_cases": [
                {"name": "State v. Brown (2018)", "type": "4th Amendment", "outcome": "Evidence admitted despite questionable search"},
                {"name": "Wright v. Ohio (2015)", "type": "Death Penalty", "outcome": "Death sentence upheld on appeal"},
            ],
            "bio_summary": "A three-decade veteran of the bench, Judge Pierce is known for conservative legal interpretation. His 4th Amendment rulings heavily favor law enforcement.",
        },
        {
            "id": "judge-005",
            "name": "Hon. Aisha Thompson",
            "court": "Cook County Family Court, Illinois",
            "jurisdiction": "State Family",
            "location": "Chicago, IL",
            "years_on_bench": 12,
            "total_cases": 2341,
            "appointed_by": "Appointed (2013)",
            "education": "Northwestern Pritzker School of Law",
            "case_types": ["Family", "Custody", "Domestic Violence", "Juvenile"],
            "ruling_breakdown": {
                "mother_custody_pct": 71,
                "father_custody_pct": 16,
                "joint_custody_pct": 13,
                "dv_orders_granted_pct": 89,
            },
            "demographic_patterns": {
                "white": {"favorable_outcome": 68, "avg_child_support_pct_above_guideline": 5},
                "black": {"favorable_outcome": 72, "avg_child_support_pct_above_guideline": 8},
                "hispanic": {"favorable_outcome": 70, "avg_child_support_pct_above_guideline": 7},
                "asian": {"favorable_outcome": 67, "avg_child_support_pct_above_guideline": 4},
            },
            "bias_score": 38,
            "bias_risk": "low-medium",
            "bias_indicators": [
                "Custody awards to mothers at 71% vs. national average of 65%",
                "Possible gender bias in custody determinations against fathers",
                "Consistently awards child support above statutory guidelines",
            ],
            "notable_cases": [
                {"name": "In re: Smith Custody (2022)", "type": "Custody", "outcome": "Sole custody to mother despite equal parenting history"},
                {"name": "Johnson v. Johnson (2020)", "type": "Domestic Violence", "outcome": "Protective order granted within 24 hours"},
            ],
            "bio_summary": "Judge Thompson is a strong child welfare advocate. While she is lauded for swift domestic violence protections, her custody decisions show a statistical lean toward mothers.",
        },
        {
            "id": "judge-006",
            "name": "Hon. David Kim",
            "court": "U.S. District Court, W.D. Washington",
            "jurisdiction": "Federal",
            "location": "Seattle, WA",
            "years_on_bench": 18,
            "total_cases": 4562,
            "appointed_by": "Bush Administration (2007)",
            "education": "Georgetown University Law Center",
            "case_types": ["Civil", "Corporate", "IP/Patent", "Employment"],
            "ruling_breakdown": {
                "plaintiff_win_pct": 33,
                "defendant_win_pct": 67,
                "settlement_rate_pct": 41,
            },
            "demographic_patterns": {
                "white": {"favorable_outcome": 42, "avg_damages_awarded_pct": 68},
                "black": {"favorable_outcome": 28, "avg_damages_awarded_pct": 41},
                "hispanic": {"favorable_outcome": 31, "avg_damages_awarded_pct": 45},
                "asian": {"favorable_outcome": 45, "avg_damages_awarded_pct": 72},
            },
            "bias_score": 71,
            "bias_risk": "high",
            "bias_indicators": [
                "Dismisses employment discrimination cases 3x above national average",
                "Favors corporate defendants in 73% of IP/patent disputes",
                "Labor law: rules against workers 71% of the time",
                "Significant campaign contribution ties to business community pre-appointment",
            ],
            "notable_cases": [
                {"name": "Martinez v. Amazon (2021)", "type": "Employment Discrimination", "outcome": "Dismissed at summary judgment"},
                {"name": "Google v. Innovate Corp (2019)", "type": "Patent", "outcome": "Ruled for Google (large corporation)"},
            ],
            "bio_summary": "Judge Kim's civil court record is strongly pro-corporate. Employment discrimination and labor cases rarely succeed before him, drawing criticism from labor advocates.",
        },
    ]


def get_laws_data():
    return [
        # Criminal
        {"id": "law-001", "code": "18 U.S.C. § 1341", "title": "Mail Fraud", "category": "Criminal", "applicable_case_types": ["criminal", "fraud", "corporate"], "summary": "Prohibits using postal service or interstate carriers to execute a scheme to defraud. Penalties up to 20 years imprisonment.", "max_penalty": "20 years / $250,000 fine"},
        {"id": "law-002", "code": "18 U.S.C. § 1343", "title": "Wire Fraud", "category": "Criminal", "applicable_case_types": ["criminal", "fraud", "corporate"], "summary": "Prohibits use of wire, radio, or TV in interstate commerce as part of scheme to defraud. Often paired with mail fraud charges.", "max_penalty": "20 years / $250,000 fine"},
        {"id": "law-003", "code": "18 U.S.C. § 922(g)", "title": "Unlawful Possession of a Firearm", "category": "Criminal", "applicable_case_types": ["criminal", "firearms"], "summary": "Prohibits possession of firearms by felons, domestic violence offenders, fugitives, and others. Mandatory minimum sentencing guidelines apply.", "max_penalty": "10 years (up to life for prior felonies)"},
        {"id": "law-004", "code": "21 U.S.C. § 841", "title": "Drug Trafficking", "category": "Criminal", "applicable_case_types": ["criminal", "drug"], "summary": "Prohibits manufacture, distribution, or possession with intent to distribute controlled substances. Penalties scale with drug type and quantity.", "max_penalty": "Life imprisonment (Schedule I/II substances)"},
        {"id": "law-005", "code": "18 U.S.C. § 1951", "title": "Hobbs Act Robbery", "category": "Criminal", "applicable_case_types": ["criminal", "robbery"], "summary": "Federal anti-extortion statute covering robbery affecting interstate commerce. Often used in organized crime prosecutions.", "max_penalty": "20 years"},
        # Civil Rights
        {"id": "law-006", "code": "42 U.S.C. § 1983", "title": "Civil Rights Act - Section 1983", "category": "Civil Rights", "applicable_case_types": ["civil rights", "police misconduct", "constitutional"], "summary": "Provides private right of action for constitutional violations by state actors. Primary tool for civil rights litigation against police and government.", "max_penalty": "Civil damages + injunctive relief"},
        {"id": "law-007", "code": "42 U.S.C. § 2000e", "title": "Title VII of the Civil Rights Act", "category": "Civil Rights", "applicable_case_types": ["employment", "discrimination", "civil rights"], "summary": "Prohibits employment discrimination based on race, color, religion, sex, or national origin. Applies to employers with 15+ employees.", "max_penalty": "Compensatory + punitive damages up to $300,000"},
        {"id": "law-008", "code": "29 U.S.C. § 623", "title": "Age Discrimination in Employment Act (ADEA)", "category": "Civil Rights", "applicable_case_types": ["employment", "age discrimination"], "summary": "Prohibits discrimination against employees 40+ years old. Covers hiring, firing, pay, job assignments, promotions, and training.", "max_penalty": "Lost wages + liquidated damages + attorney fees"},
        # Family
        {"id": "law-009", "code": "UCC Article 3", "title": "Uniform Child Custody Jurisdiction Act", "category": "Family", "applicable_case_types": ["family", "custody"], "summary": "Governs jurisdiction for child custody proceedings. Establishes 'home state' jurisdiction rules to prevent forum shopping.", "max_penalty": "N/A - Family court jurisdiction"},
        {"id": "law-010", "code": "18 U.S.C. § 2261", "title": "Interstate Domestic Violence", "category": "Family/Criminal", "applicable_case_types": ["domestic violence", "family", "criminal"], "summary": "Federal crime to travel across state lines with intent to injure, harass, or intimidate a spouse/partner. Includes cyberstalking.", "max_penalty": "Life imprisonment (if death results)"},
        # Constitutional
        {"id": "law-011", "code": "U.S. Const. Amend. IV", "title": "Fourth Amendment — Search & Seizure", "category": "Constitutional", "applicable_case_types": ["criminal", "civil rights", "constitutional"], "summary": "Protects against unreasonable searches and seizures. Requires warrants based on probable cause. Evidence obtained in violation may be suppressed (exclusionary rule).", "max_penalty": "N/A - Constitutional protection"},
        {"id": "law-012", "code": "U.S. Const. Amend. V", "title": "Fifth Amendment — Self-Incrimination & Due Process", "category": "Constitutional", "applicable_case_types": ["criminal", "constitutional"], "summary": "Right against self-incrimination (Miranda), double jeopardy protection, due process requirement. Grand jury requirement for serious federal crimes.", "max_penalty": "N/A - Constitutional protection"},
        {"id": "law-013", "code": "U.S. Const. Amend. XIV", "title": "Fourteenth Amendment — Equal Protection", "category": "Constitutional", "applicable_case_types": ["civil rights", "constitutional", "discrimination"], "summary": "Guarantees equal protection under the law. Primary constitutional basis for challenging discriminatory government action. Key standard: suspect classification triggers strict scrutiny.", "max_penalty": "N/A - Constitutional protection"},
        # Corporate
        {"id": "law-014", "code": "15 U.S.C. § 78j(b)", "title": "Securities Exchange Act — Rule 10b-5", "category": "Corporate", "applicable_case_types": ["corporate", "fraud", "securities"], "summary": "Prohibits fraudulent activity in connection with purchase or sale of securities. Foundation of securities fraud litigation.", "max_penalty": "20 years + $5 million fine (criminal); civil disgorgement"},
        {"id": "law-015", "code": "18 U.S.C. § 1962", "title": "RICO Act — Racketeer Influenced Corrupt Organizations", "category": "Criminal/Corporate", "applicable_case_types": ["criminal", "corporate", "organized crime"], "summary": "Prohibits patterns of racketeering activity in connection with enterprise. Civil RICO allows treble damages. Wide prosecutorial discretion.", "max_penalty": "20 years per count + asset forfeiture"},
    ]
