"""Enhanced seed data — Indian judges with full bias intelligence profiles."""


def _grade(score):
    if score <= 20: return "A"
    if score <= 40: return "B"
    if score <= 60: return "C"
    if score <= 75: return "D"
    return "F"


def get_judge_data():
    return [
        {
            "id": "judge-001",
            "name": "Justice D.Y. Chandrachud",
            "court": "Supreme Court of India",
            "jurisdiction": "Supreme Court",
            "location": "New Delhi",
            "years_on_bench": 26,
            "total_cases": 9247,
            "appointed_by": "Elevated as 50th CJI — Nov 2022",
            "education": "Delhi University; Harvard Law School (LL.M., S.J.D.)",
            "case_types": ["Constitutional", "Criminal", "Civil Rights", "Family"],
            "ruling_breakdown": {"prosecution_win_pct": 61, "defense_win_pct": 39, "appeals_reversed_pct": 14},
            "demographic_patterns": {
                "general_upper_caste": {"conviction_rate": 62, "avg_sentence_months": 28},
                "obc": {"conviction_rate": 60, "avg_sentence_months": 27},
                "sc_st": {"conviction_rate": 61, "avg_sentence_months": 28},
                "minority": {"conviction_rate": 59, "avg_sentence_months": 26},
            },
            "bias_score": 15,
            "bias_risk": "low",
            "bias_indicators": [
                "Conviction rates differ by less than 3% across all socioeconomic groups",
                "Authored landmark verdicts striking down discriminatory laws (Section 377, adultery)",
                "Consistently applies constitutional morality over social morality",
            ],
            "bias_breakdown": {
                "caste_religious": {
                    "score": 12, "grade": "A",
                    "label": "Caste / Religious Bias",
                    "data_points": [
                        {"metric": "SC/ST vs. General conviction gap", "value": "+3%", "benchmark": "Threshold: +5%", "status": "pass"},
                        {"metric": "Minority avg. sentence disparity", "value": "+2 months", "benchmark": "Threshold: +4 months", "status": "pass"},
                        {"metric": "Bail denial rate — SC/ST vs. General", "value": "+2%", "benchmark": "Threshold: +8%", "status": "pass"},
                    ],
                    "verdict": "No statistically significant caste or religious bias detected. Outcomes are equitable across community lines.",
                },
                "gender": {
                    "score": 18, "grade": "A",
                    "label": "Gender Bias",
                    "data_points": [
                        {"metric": "Male vs. female defendant conviction gap", "value": "+4%", "benchmark": "Threshold: +8%", "status": "pass"},
                        {"metric": "Women's bail denial rate", "value": "28%", "benchmark": "National avg: 41%", "status": "pass"},
                        {"metric": "POCSO/DV case outcome for survivors", "value": "Favorable 74%", "benchmark": "National avg: 61%", "status": "pass"},
                    ],
                    "verdict": "Above-average gender equity. Known for progressive interpretations of marital rights and women's bodily autonomy.",
                },
                "socioeconomic": {
                    "score": 28, "grade": "B",
                    "label": "Socioeconomic Bias",
                    "data_points": [
                        {"metric": "Bail: affluent vs. legal aid defendants", "value": "+9% grant gap", "benchmark": "Threshold: +15%", "status": "pass"},
                        {"metric": "Sentence length: top vs. bottom economic decile", "value": "+5 months", "benchmark": "Threshold: +8 months", "status": "pass"},
                        {"metric": "Legal aid quality correlation with outcome", "value": "12% impact", "benchmark": "Threshold: 20%", "status": "pass"},
                    ],
                    "verdict": "Mild socioeconomic gradient present — consistent with systemic resource disparities — but not statistically alarming.",
                },
                "recidivism": {
                    "score": 14, "grade": "A",
                    "label": "Recidivism Bias",
                    "data_points": [
                        {"metric": "First offender vs. repeat offender sentence uplift", "value": "+18%", "benchmark": "Guideline: +15–25%", "status": "pass"},
                        {"metric": "Bail denial: first offender vs. prior record", "value": "+14%", "benchmark": "Threshold: +25%", "status": "pass"},
                        {"metric": "Diversion/probation for first offenders", "value": "29%", "benchmark": "National avg: 18%", "status": "pass"},
                    ],
                    "verdict": "Highly proportionate treatment of recidivism. Prior criminal history is considered but not amplified beyond guideline ranges.",
                },
                "geographic": {
                    "score": 10, "grade": "A",
                    "label": "Geographic / Regional Bias",
                    "data_points": [
                        {"metric": "Urban vs. rural defendant outcome gap", "value": "+2%", "benchmark": "Threshold: +6%", "status": "pass"},
                        {"metric": "North vs. South India case outcome variance", "value": "1.5%", "benchmark": "Threshold: +5%", "status": "pass"},
                    ],
                    "verdict": "No detectable geographic or regional bias. Outcomes are consistent regardless of defendant's state of origin.",
                },
            },
            "report_card": {"overall": "A", "caste_religious": "A", "gender": "A", "socioeconomic": "B", "recidivism": "A", "geographic": "A"},
            "comparable_cases": [
                {
                    "crime": "IPC § 302 — Culpable Homicide (circumstantial evidence, no eyewitnesses)",
                    "year": 2021,
                    "defendant_a": {"community": "SC (Dalit)", "gender": "Male", "economic_class": "Below Poverty Line", "counsel": "Legal Aid", "outcome": "CONVICTED", "sentence": "Life Imprisonment", "bail_on_appeal": "DENIED"},
                    "defendant_b": {"community": "Upper Caste (Brahmin)", "gender": "Male", "economic_class": "Affluent", "counsel": "Senior Advocate", "outcome": "CONVICTED", "sentence": "Life Imprisonment", "bail_on_appeal": "GRANTED"},
                    "observation": "Same conviction — but bail pending appeal denied for Dalit defendant, granted for upper-caste. Socioeconomic disparity, not caste-specific ruling.",
                    "bias_type": "socioeconomic",
                },
                {
                    "crime": "CrPC § 438 — Anticipatory Bail (NDPS Act, small quantity possession)",
                    "year": 2023,
                    "defendant_a": {"community": "Muslim", "gender": "Male", "economic_class": "Working Class", "counsel": "District Court Lawyer", "outcome": "BAIL DENIED", "sentence": "N/A", "bail_on_appeal": "N/A"},
                    "defendant_b": {"community": "Upper Caste Hindu", "gender": "Male", "economic_class": "Middle Class", "counsel": "Experienced HC Advocate", "outcome": "BAIL GRANTED", "sentence": "N/A", "bail_on_appeal": "N/A"},
                    "observation": "Bail outcome differed — Chandrachud's own bench subsequently set aside the lower court denial. Systemic inequality at lower court level, not at his level.",
                    "bias_type": "caste_religious",
                },
            ],
            "timeline": [
                {"year": 2018, "conviction_rate": 59, "avg_sentence_months": 27, "bail_denial_rate": 38, "notable": "Sabarimala verdict — allowed women entry"},
                {"year": 2019, "conviction_rate": 61, "avg_sentence_months": 28, "bail_denial_rate": 40, "notable": "Ayodhya verdict — part of 5-judge bench"},
                {"year": 2020, "conviction_rate": 60, "avg_sentence_months": 27, "bail_denial_rate": 39, "notable": "COVID: expanded virtual court hearings"},
                {"year": 2021, "conviction_rate": 62, "avg_sentence_months": 28, "bail_denial_rate": 41, "notable": "Article 370 aftermath cases"},
                {"year": 2022, "conviction_rate": 61, "avg_sentence_months": 28, "bail_denial_rate": 40, "notable": "Elevated to CJI in November"},
                {"year": 2023, "conviction_rate": 63, "avg_sentence_months": 29, "bail_denial_rate": 42, "notable": "Electoral bonds — petitions filed"},
                {"year": 2024, "conviction_rate": 62, "avg_sentence_months": 28, "bail_denial_rate": 40, "notable": "Electoral bonds declared unconstitutional"},
            ],
            "temporal_patterns": {
                "day_of_week": [
                    {"day": "Mon", "conviction_rate": 63, "bail_denial_rate": 43},
                    {"day": "Tue", "conviction_rate": 62, "bail_denial_rate": 41},
                    {"day": "Wed", "conviction_rate": 61, "bail_denial_rate": 40},
                    {"day": "Thu", "conviction_rate": 61, "bail_denial_rate": 40},
                    {"day": "Fri", "conviction_rate": 60, "bail_denial_rate": 38},
                ],
                "time_of_day": [
                    {"slot": "9–11am", "bail_denial_rate": 42, "label": "Morning"},
                    {"slot": "11am–1pm", "bail_denial_rate": 38, "label": "Pre-Lunch"},
                    {"slot": "2–4pm", "bail_denial_rate": 41, "label": "Post-Lunch"},
                    {"slot": "4–6pm", "bail_denial_rate": 36, "label": "Late"},
                ],
                "election_year_effect": {"election_year_conviction_rate": 63, "normal_year_rate": 61, "difference": "+2%", "assessment": "Minimal election effect — consistent with strong judicial independence"},
                "media_effect": {"high_profile_rate": 64, "routine_rate": 61, "difference": "+3%", "assessment": "Marginal increase in high-profile matters — statistically within noise"},
                "monday_effect": "+3pp above weekly average",
                "lunch_effect": "-4pp bail denial rate post-lunch vs. pre-lunch",
            },
            "outlier_score": {
                "score": -22, "direction": "below",
                "this_judge_conviction_rate": 61, "peer_avg": 73,
                "deviation": "22 percentage points below Supreme Court peers",
                "percentile": 11,
                "label": "Among the most defendant-protective judges on the Supreme Court",
            },
            "notable_cases": [
                {"name": "Navtej Singh Johar v. UoI (2018)", "type": "Constitutional", "outcome": "Section 377 decriminalized — landmark LGBTQ rights verdict"},
                {"name": "Electoral Bonds Case (2024)", "type": "Constitutional", "outcome": "Electoral bonds declared unconstitutional — transparency upheld"},
                {"name": "K.S. Puttaswamy v. UoI (2017)", "type": "Constitutional", "outcome": "Right to Privacy recognized as fundamental right under Article 21"},
            ],
            "bio_summary": "Justice Chandrachud is widely regarded as one of India's most consequential jurists. He authored landmark verdicts on privacy, LGBTQ rights, and electoral transparency. Son of former CJI Y.V. Chandrachud, he is known for constitutional morality over social morality.",
        },

        {
            "id": "judge-002",
            "name": "Justice Arun Kumar Mishra",
            "court": "Supreme Court of India",
            "jurisdiction": "Supreme Court",
            "location": "New Delhi",
            "years_on_bench": 18,
            "total_cases": 4823,
            "appointed_by": "Elevated to SC — July 2014 (Retired Sept 2020)",
            "education": "Government Law College, Gwalior",
            "case_types": ["Criminal", "Land Acquisition", "UAPA", "Constitutional"],
            "ruling_breakdown": {"prosecution_win_pct": 87, "defense_win_pct": 13, "appeals_reversed_pct": 34},
            "demographic_patterns": {
                "general_upper_caste": {"conviction_rate": 75, "avg_sentence_months": 22},
                "obc": {"conviction_rate": 88, "avg_sentence_months": 38},
                "sc_st": {"conviction_rate": 91, "avg_sentence_months": 44},
                "minority": {"conviction_rate": 89, "avg_sentence_months": 41},
            },
            "bias_score": 81,
            "bias_risk": "high",
            "bias_indicators": [
                "16% higher conviction rate for SC/ST vs. General defendants",
                "22-month average sentencing disparity between marginalized and privileged defendants",
                "34% appeal reversal rate — more than double the court average of 15%",
                "Bail denied to UAPA accused at 94% rate — widely criticized by civil liberty advocates",
            ],
            "bias_breakdown": {
                "caste_religious": {
                    "score": 82, "grade": "F",
                    "label": "Caste / Religious Bias",
                    "data_points": [
                        {"metric": "SC/ST vs. General conviction gap", "value": "+16%", "benchmark": "Threshold: +5%", "status": "fail"},
                        {"metric": "Minority sentence disparity", "value": "+19 months", "benchmark": "Threshold: +4 months", "status": "fail"},
                        {"metric": "Bail denial: SC/ST vs. General", "value": "+31%", "benchmark": "Threshold: +8%", "status": "fail"},
                    ],
                    "verdict": "Severe and statistically unambiguous bias against SC/ST and minority defendants. Conviction rates and sentencing show extreme disparity.",
                },
                "gender": {
                    "score": 65, "grade": "D",
                    "label": "Gender Bias",
                    "data_points": [
                        {"metric": "Male SC/ST vs. female upper-caste sentencing", "value": "2.4x longer", "benchmark": "Threshold: 1.5x", "status": "fail"},
                        {"metric": "Women bail denial in criminal cases", "value": "62%", "benchmark": "National avg: 41%", "status": "fail"},
                        {"metric": "Domestic violence cases outcome for survivors", "value": "Favorable 38%", "benchmark": "National avg: 61%", "status": "fail"},
                    ],
                    "verdict": "Significant gender inequity, especially when gender and caste intersect. Female survivors of domestic violence fared poorly in his court.",
                },
                "socioeconomic": {
                    "score": 78, "grade": "F",
                    "label": "Socioeconomic Bias",
                    "data_points": [
                        {"metric": "Corporate fraud defendant conviction rate", "value": "31%", "benchmark": "National avg: 67%", "status": "fail"},
                        {"metric": "Below-poverty-line defendant conviction rate", "value": "91%", "benchmark": "National avg: 68%", "status": "fail"},
                        {"metric": "Legal aid client vs. Senior Advocate outcome gap", "value": "+38%", "benchmark": "Threshold: +15%", "status": "fail"},
                    ],
                    "verdict": "Extreme economic class disparity. Corporate defendants were acquitted or given nominal sentences while economically disadvantaged defendants faced harsh outcomes.",
                },
                "recidivism": {
                    "score": 85, "grade": "F",
                    "label": "Recidivism Bias",
                    "data_points": [
                        {"metric": "First offender vs. repeat: sentence uplift", "value": "+67%", "benchmark": "Guideline: +15–25%", "status": "fail"},
                        {"metric": "Any prior FIR = bail denied rate", "value": "89%", "benchmark": "National avg: 52%", "status": "fail"},
                        {"metric": "Diversion for first-time minor offenders", "value": "3%", "benchmark": "National avg: 18%", "status": "fail"},
                    ],
                    "verdict": "Prior criminal record — even dismissed FIRs — dramatically increased adverse outcomes, well beyond any proportionality standard.",
                },
                "geographic": {
                    "score": 63, "grade": "D",
                    "label": "Geographic / Regional Bias",
                    "data_points": [
                        {"metric": "Rural vs. urban defendant sentence gap", "value": "+14 months", "benchmark": "Threshold: +4 months", "status": "fail"},
                        {"metric": "Minority-majority region case outcome variance", "value": "22%", "benchmark": "Threshold: +5%", "status": "fail"},
                    ],
                    "verdict": "Rural defendants and those from minority-concentrated districts faced significantly harsher outcomes.",
                },
            },
            "report_card": {"overall": "F", "caste_religious": "F", "gender": "D", "socioeconomic": "F", "recidivism": "F", "geographic": "D"},
            "comparable_cases": [
                {
                    "crime": "NDPS Act — Intermediate Quantity Possession (identical weight, identical circumstances)",
                    "year": 2019,
                    "defendant_a": {"community": "SC (Chamar)", "gender": "Male", "economic_class": "Daily Wage Worker", "counsel": "Legal Aid", "outcome": "CONVICTED", "sentence": "10 Years RI + ₹1L Fine", "bail_on_appeal": "DENIED"},
                    "defendant_b": {"community": "Upper Caste (Rajput)", "gender": "Male", "economic_class": "Business Owner", "counsel": "Senior Advocate (2 Sr Advocates)", "outcome": "ACQUITTED", "sentence": "N/A", "bail_on_appeal": "N/A"},
                    "observation": "Identical evidence, identical quantity. SC defendant convicted with maximum term. Upper-caste defendant acquitted. A stark 34% appeal reversal on this case.",
                    "bias_type": "caste_religious",
                },
                {
                    "crime": "IPC § 420 — Corporate Fraud (₹180 Cr vs ₹2 Cr — proportional schemes)",
                    "year": 2018,
                    "defendant_a": {"community": "OBC", "gender": "Male", "economic_class": "Small Business", "counsel": "District Court Lawyer", "outcome": "CONVICTED", "sentence": "4 Years + ₹50L Fine", "bail_on_appeal": "DENIED"},
                    "defendant_b": {"community": "Upper Caste", "gender": "Male", "economic_class": "Industrialist", "counsel": "2 Senior Advocates", "outcome": "ACQUITTED", "sentence": "N/A", "bail_on_appeal": "N/A"},
                    "observation": "The larger corporate fraud was acquitted; the smaller fraud by a small businessman resulted in conviction. A textbook socioeconomic disparity.",
                    "bias_type": "socioeconomic",
                },
                {
                    "crime": "UAPA § 15 — Terrorism charge (both cases: bail applications, similar charges, no conviction yet)",
                    "year": 2020,
                    "defendant_a": {"community": "Muslim", "gender": "Male", "economic_class": "Academic / Researcher", "counsel": "HC Advocate", "outcome": "BAIL DENIED", "sentence": "Undertrial — 3+ years", "bail_on_appeal": "DENIED (twice)"},
                    "defendant_b": {"community": "Hindu", "gender": "Male", "economic_class": "Retired Govt Officer", "counsel": "Senior Advocate", "outcome": "BAIL GRANTED", "sentence": "N/A", "bail_on_appeal": "N/A"},
                    "observation": "Two UAPA bail applications heard in the same month. Muslim academic denied bail. Hindu former official granted bail. Identical charge quality per case records.",
                    "bias_type": "caste_religious",
                },
            ],
            "timeline": [
                {"year": 2018, "conviction_rate": 83, "avg_sentence_months": 38, "bail_denial_rate": 71, "notable": "First full year — pattern begins to emerge"},
                {"year": 2019, "conviction_rate": 87, "avg_sentence_months": 40, "bail_denial_rate": 78, "notable": "Election year — conviction rate peaks"},
                {"year": 2020, "conviction_rate": 89, "avg_sentence_months": 42, "bail_denial_rate": 82, "notable": "Elgar Parishad bail denials — peak controversy"},
                {"year": 2020, "conviction_rate": 91, "avg_sentence_months": 44, "bail_denial_rate": 84, "notable": "Praised PM at international event — conflict of interest raised"},
                {"year": 2020, "conviction_rate": 87, "avg_sentence_months": 41, "bail_denial_rate": 80, "notable": "Final year — retired Sept 2020"},
            ],
            "temporal_patterns": {
                "day_of_week": [
                    {"day": "Mon", "conviction_rate": 91, "bail_denial_rate": 87},
                    {"day": "Tue", "conviction_rate": 88, "bail_denial_rate": 82},
                    {"day": "Wed", "conviction_rate": 86, "bail_denial_rate": 80},
                    {"day": "Thu", "conviction_rate": 88, "bail_denial_rate": 81},
                    {"day": "Fri", "conviction_rate": 84, "bail_denial_rate": 77},
                ],
                "time_of_day": [
                    {"slot": "9–11am", "bail_denial_rate": 89, "label": "Morning"},
                    {"slot": "11am–1pm", "bail_denial_rate": 92, "label": "Pre-Lunch"},
                    {"slot": "2–4pm", "bail_denial_rate": 81, "label": "Post-Lunch"},
                    {"slot": "4–6pm", "bail_denial_rate": 74, "label": "Late"},
                ],
                "election_year_effect": {"election_year_conviction_rate": 91, "normal_year_rate": 83, "difference": "+8%", "assessment": "Sharp spike in election years — conviction rate rose 8pp in 2019. Pattern consistent with political alignment concerns."},
                "media_effect": {"high_profile_rate": 93, "routine_rate": 82, "difference": "+11%", "assessment": "High-profile and politically sensitive cases saw markedly worse outcomes for defendants — 11pp above routine case rate."},
                "monday_effect": "+7pp above weekly average — 'Maximum Monday' pattern",
                "lunch_effect": "+11pp bail denial rate pre-lunch vs. post-lunch — extreme decision fatigue indicator",
            },
            "outlier_score": {
                "score": 19, "direction": "above",
                "this_judge_conviction_rate": 87, "peer_avg": 68,
                "deviation": "19 percentage points above Supreme Court peers",
                "percentile": 97,
                "label": "Among the 3% most prosecution-friendly judges — extreme outlier",
            },
            "notable_cases": [
                {"name": "Elgar Parishad (2020)", "type": "UAPA", "outcome": "Denied bail to academics/activists — several reversed by later benches"},
                {"name": "Land Acquisition Retroactive (2019)", "type": "Land / Constitutional", "outcome": "Ruling overturned by larger bench of 5 judges"},
                {"name": "'Most Versatile Genius' Speech (2020)", "type": "Ethical", "outcome": "Recusal demands ignored — judicial independence questions raised"},
            ],
            "bio_summary": "Justice Mishra's tenure was among the most controversial in recent SC history. His 34% reversal rate and extreme demographic sentencing disparities drew sustained criticism. His participation at a government event praising the PM created a perception of political alignment.",
        },

        {
            "id": "judge-003",
            "name": "Justice Sanjiv Khanna",
            "court": "Supreme Court of India",
            "jurisdiction": "Supreme Court",
            "location": "New Delhi",
            "years_on_bench": 20,
            "total_cases": 6112,
            "appointed_by": "51st Chief Justice of India — Nov 2024",
            "education": "Campus Law Centre, Delhi University",
            "case_types": ["Criminal", "Constitutional", "Taxation", "Electoral"],
            "ruling_breakdown": {"prosecution_win_pct": 68, "defense_win_pct": 32, "appeals_reversed_pct": 11},
            "demographic_patterns": {
                "general_upper_caste": {"conviction_rate": 67, "avg_sentence_months": 24},
                "obc": {"conviction_rate": 69, "avg_sentence_months": 26},
                "sc_st": {"conviction_rate": 70, "avg_sentence_months": 27},
                "minority": {"conviction_rate": 68, "avg_sentence_months": 25},
            },
            "bias_score": 32,
            "bias_risk": "low",
            "bias_indicators": [
                "Demographic conviction disparity within 3% — well within statistical margin",
                "Authored VVPAT judgment establishing right to paper trail in elections",
                "Consistent bail jurisprudence across all community groups",
            ],
            "bias_breakdown": {
                "caste_religious": {"score": 35, "grade": "B", "label": "Caste / Religious Bias",
                    "data_points": [
                        {"metric": "SC/ST vs. General conviction gap", "value": "+3%", "benchmark": "Threshold: +5%", "status": "pass"},
                        {"metric": "Minority sentence disparity", "value": "+1 month", "benchmark": "Threshold: +4 months", "status": "pass"},
                    ], "verdict": "Very minor statistical variations within acceptable range. No systemic bias pattern detected."},
                "gender": {"score": 30, "grade": "B", "label": "Gender Bias",
                    "data_points": [
                        {"metric": "Male vs. female conviction gap", "value": "+5%", "benchmark": "Threshold: +8%", "status": "pass"},
                        {"metric": "Domestic violence survivor outcome", "value": "Favorable 65%", "benchmark": "National avg: 61%", "status": "pass"},
                    ], "verdict": "Broadly equitable. Slightly above national average in favorable DV outcomes for survivors."},
                "socioeconomic": {"score": 42, "grade": "C", "label": "Socioeconomic Bias",
                    "data_points": [
                        {"metric": "Bail: affluent vs. legal aid gap", "value": "+14% grant gap", "benchmark": "Threshold: +15%", "status": "warn"},
                        {"metric": "Sentence: top vs. bottom economic decile", "value": "+6 months", "benchmark": "Threshold: +8 months", "status": "pass"},
                    ], "verdict": "Moderate socioeconomic gradient — reflective of systemic resource inequality rather than personal bias."},
                "recidivism": {"score": 45, "grade": "C", "label": "Recidivism Bias",
                    "data_points": [
                        {"metric": "Repeat offender sentence uplift", "value": "+28%", "benchmark": "Guideline: +15–25%", "status": "warn"},
                        {"metric": "Bail denial for prior record holders", "value": "+22%", "benchmark": "Threshold: +25%", "status": "pass"},
                    ], "verdict": "Slightly elevated recidivism weighting — modestly above guideline ranges but not grossly disproportionate."},
                "geographic": {"score": 22, "grade": "A", "label": "Geographic / Regional Bias",
                    "data_points": [
                        {"metric": "Urban vs. rural outcome gap", "value": "+3%", "benchmark": "Threshold: +6%", "status": "pass"},
                    ], "verdict": "No geographic bias pattern detected."},
            },
            "report_card": {"overall": "B", "caste_religious": "B", "gender": "B", "socioeconomic": "C", "recidivism": "C", "geographic": "A"},
            "comparable_cases": [
                {
                    "crime": "IPC § 498A — Matrimonial Cruelty (similar FIRs, similar evidence quality)",
                    "year": 2022,
                    "defendant_a": {"community": "OBC", "gender": "Male", "economic_class": "Working Class", "counsel": "District Lawyer", "outcome": "CONVICTED", "sentence": "2 Years + Fine", "bail_on_appeal": "DENIED initially"},
                    "defendant_b": {"community": "General", "gender": "Male", "economic_class": "Middle Class", "counsel": "HC Advocate", "outcome": "ACQUITTED", "sentence": "N/A", "bail_on_appeal": "N/A"},
                    "observation": "Outcome differed by socioeconomic access to better counsel rather than caste directly. Illustrates structural inequality in the system.",
                    "bias_type": "socioeconomic",
                },
            ],
            "timeline": [
                {"year": 2018, "conviction_rate": 65, "avg_sentence_months": 23, "bail_denial_rate": 42, "notable": "Elevated to Supreme Court"},
                {"year": 2019, "conviction_rate": 67, "avg_sentence_months": 24, "bail_denial_rate": 44, "notable": "Election year — marginal uptick"},
                {"year": 2020, "conviction_rate": 66, "avg_sentence_months": 24, "bail_denial_rate": 43, "notable": "COVID — reduced physical hearings"},
                {"year": 2021, "conviction_rate": 68, "avg_sentence_months": 25, "bail_denial_rate": 45, "notable": "Article 370 review cases"},
                {"year": 2022, "conviction_rate": 69, "avg_sentence_months": 26, "bail_denial_rate": 46, "notable": "Electoral bonds petitions"},
                {"year": 2023, "conviction_rate": 68, "avg_sentence_months": 25, "bail_denial_rate": 44, "notable": "VVPAT judgment — landmark"},
                {"year": 2024, "conviction_rate": 70, "avg_sentence_months": 27, "bail_denial_rate": 47, "notable": "Elevated to CJI in November"},
            ],
            "temporal_patterns": {
                "day_of_week": [
                    {"day": "Mon", "conviction_rate": 71, "bail_denial_rate": 49},
                    {"day": "Tue", "conviction_rate": 69, "bail_denial_rate": 46},
                    {"day": "Wed", "conviction_rate": 68, "bail_denial_rate": 44},
                    {"day": "Thu", "conviction_rate": 68, "bail_denial_rate": 45},
                    {"day": "Fri", "conviction_rate": 66, "bail_denial_rate": 42},
                ],
                "time_of_day": [
                    {"slot": "9–11am", "bail_denial_rate": 48, "label": "Morning"},
                    {"slot": "11am–1pm", "bail_denial_rate": 46, "label": "Pre-Lunch"},
                    {"slot": "2–4pm", "bail_denial_rate": 45, "label": "Post-Lunch"},
                    {"slot": "4–6pm", "bail_denial_rate": 41, "label": "Late"},
                ],
                "election_year_effect": {"election_year_conviction_rate": 69, "normal_year_rate": 67, "difference": "+2%", "assessment": "Negligible election year effect — consistent judicial independence"},
                "media_effect": {"high_profile_rate": 71, "routine_rate": 67, "difference": "+4%", "assessment": "Small uptick in high-profile cases — largely explained by case complexity, not media pressure"},
                "monday_effect": "+3pp above weekly average",
                "lunch_effect": "-4pp bail denial post-lunch",
            },
            "outlier_score": {"score": -5, "direction": "below", "this_judge_conviction_rate": 68, "peer_avg": 73, "deviation": "5 percentage points below SC peers", "percentile": 35, "label": "Slightly below average — broadly in line with institutional norms"},
            "notable_cases": [
                {"name": "Electoral Bonds Case (2024)", "type": "Constitutional / Electoral", "outcome": "Part of unanimous 5-judge bench — bonds declared unconstitutional"},
                {"name": "VVPAT Case (2024)", "type": "Electoral", "outcome": "Established VVPAT verification guidelines — protected electoral integrity"},
            ],
            "bio_summary": "Justice Khanna became the 51st CJI in November 2024. Known for careful, measured judgments and a low reversal rate. His electoral jurisprudence has strengthened democratic accountability. Nephew of Justice H.R. Khanna, who famously dissented in the ADM Jabalpur case.",
        },

        {
            "id": "judge-004",
            "name": "Justice G.S. Patel",
            "court": "Bombay High Court",
            "jurisdiction": "High Court",
            "location": "Mumbai, Maharashtra",
            "years_on_bench": 12,
            "total_cases": 3891,
            "appointed_by": "Elevated to Bombay HC — 2013 (Resigned 2023)",
            "education": "Government Law College, Mumbai; Gray's Inn, London (Barrister)",
            "case_types": ["Civil", "IP/Copyright", "LGBTQ Rights", "Corporate", "Bail"],
            "ruling_breakdown": {"prosecution_win_pct": 58, "defense_win_pct": 42, "appeals_reversed_pct": 7},
            "demographic_patterns": {
                "general_upper_caste": {"conviction_rate": 58, "avg_sentence_months": 18},
                "obc": {"conviction_rate": 57, "avg_sentence_months": 18},
                "sc_st": {"conviction_rate": 59, "avg_sentence_months": 19},
                "minority": {"conviction_rate": 58, "avg_sentence_months": 18},
            },
            "bias_score": 22,
            "bias_risk": "low",
            "bias_indicators": [
                "Uniform outcomes across all demographic groups — 2% or less variance",
                "Lowest appeal reversal rate in Bombay HC at 7%",
                "Consistently granted bail in LGBTQ and free speech related arrests",
            ],
            "bias_breakdown": {
                "caste_religious": {"score": 18, "grade": "A", "label": "Caste / Religious Bias",
                    "data_points": [
                        {"metric": "SC/ST vs. General conviction gap", "value": "+1%", "benchmark": "Threshold: +5%", "status": "pass"},
                        {"metric": "Minority sentence disparity", "value": "0 months", "benchmark": "Threshold: +4 months", "status": "pass"},
                    ], "verdict": "Exemplary equity across caste and religious lines. No measurable disparity in outcomes."},
                "gender": {"score": 15, "grade": "A", "label": "Gender Bias",
                    "data_points": [
                        {"metric": "Male vs. female conviction gap", "value": "+2%", "benchmark": "Threshold: +8%", "status": "pass"},
                        {"metric": "LGBTQ defendant outcomes", "value": "Favorable 71%", "benchmark": "National avg: 44%", "status": "pass"},
                    ], "verdict": "Outstanding. Known for protecting LGBTQ rights and gender non-conforming individuals in a system that often fails them."},
                "socioeconomic": {"score": 32, "grade": "B", "label": "Socioeconomic Bias",
                    "data_points": [
                        {"metric": "Bail: affluent vs. legal aid gap", "value": "+8% grant gap", "benchmark": "Threshold: +15%", "status": "pass"},
                        {"metric": "NDPS bail — poor defendants", "value": "Granted 41%", "benchmark": "National avg: 18%", "status": "pass"},
                    ], "verdict": "Good. Notably higher bail grant rates for poor defendants in NDPS cases through landmark bail guidelines."},
                "recidivism": {"score": 28, "grade": "B", "label": "Recidivism Bias",
                    "data_points": [
                        {"metric": "Repeat offender sentence uplift", "value": "+19%", "benchmark": "Guideline: +15–25%", "status": "pass"},
                        {"metric": "First offender diversion rate", "value": "27%", "benchmark": "National avg: 18%", "status": "pass"},
                    ], "verdict": "Proportionate recidivism weighting with above-average diversion for first offenders."},
                "geographic": {"score": 20, "grade": "A", "label": "Geographic / Regional Bias",
                    "data_points": [
                        {"metric": "Mumbai vs. outstation defendant gap", "value": "+2%", "benchmark": "Threshold: +6%", "status": "pass"},
                    ], "verdict": "No geographic bias detected within Maharashtra jurisdiction."},
            },
            "report_card": {"overall": "A", "caste_religious": "A", "gender": "A", "socioeconomic": "B", "recidivism": "B", "geographic": "A"},
            "comparable_cases": [
                {
                    "crime": "NDPS Act — Small Quantity Possession (cannabis, identical weight)",
                    "year": 2021,
                    "defendant_a": {"community": "SC (Mahar)", "gender": "Male", "economic_class": "Labourer", "counsel": "Legal Aid", "outcome": "BAIL GRANTED", "sentence": "Under trial", "bail_on_appeal": "N/A"},
                    "defendant_b": {"community": "Upper Caste", "gender": "Male", "economic_class": "College Student", "counsel": "Private Advocate", "outcome": "BAIL GRANTED", "sentence": "Under trial", "bail_on_appeal": "N/A"},
                    "observation": "Both defendants received bail — equitable outcome regardless of community or economic status. Consistent with Patel's landmark NDPS bail guidelines.",
                    "bias_type": "socioeconomic",
                },
            ],
            "timeline": [
                {"year": 2018, "conviction_rate": 55, "avg_sentence_months": 16, "bail_denial_rate": 31, "notable": "Landmark IP judgment — balanced free expression"},
                {"year": 2019, "conviction_rate": 57, "avg_sentence_months": 17, "bail_denial_rate": 33, "notable": "Election year — no change in pattern"},
                {"year": 2020, "conviction_rate": 56, "avg_sentence_months": 17, "bail_denial_rate": 32, "notable": "COVID bail orders — progressive"},
                {"year": 2021, "conviction_rate": 58, "avg_sentence_months": 18, "bail_denial_rate": 34, "notable": "NDPS bail guidelines issued"},
                {"year": 2022, "conviction_rate": 59, "avg_sentence_months": 19, "bail_denial_rate": 35, "notable": "LGBTQ civil rights rulings"},
                {"year": 2023, "conviction_rate": 58, "avg_sentence_months": 18, "bail_denial_rate": 33, "notable": "Resigned from bench — returned to practice"},
            ],
            "temporal_patterns": {
                "day_of_week": [
                    {"day": "Mon", "conviction_rate": 60, "bail_denial_rate": 37},
                    {"day": "Tue", "conviction_rate": 59, "bail_denial_rate": 35},
                    {"day": "Wed", "conviction_rate": 58, "bail_denial_rate": 33},
                    {"day": "Thu", "conviction_rate": 57, "bail_denial_rate": 33},
                    {"day": "Fri", "conviction_rate": 56, "bail_denial_rate": 30},
                ],
                "time_of_day": [
                    {"slot": "9–11am", "bail_denial_rate": 36, "label": "Morning"},
                    {"slot": "11am–1pm", "bail_denial_rate": 34, "label": "Pre-Lunch"},
                    {"slot": "2–4pm", "bail_denial_rate": 33, "label": "Post-Lunch"},
                    {"slot": "4–6pm", "bail_denial_rate": 30, "label": "Late"},
                ],
                "election_year_effect": {"election_year_conviction_rate": 57, "normal_year_rate": 58, "difference": "-1%", "assessment": "No measurable election effect — virtually flat pattern over time"},
                "media_effect": {"high_profile_rate": 59, "routine_rate": 58, "difference": "+1%", "assessment": "Negligible media influence — consistent with principled judicial independence"},
                "monday_effect": "+2pp above weekly average — very mild",
                "lunch_effect": "-2pp bail denial post-lunch — minimal fatigue effect",
            },
            "outlier_score": {"score": -15, "direction": "below", "this_judge_conviction_rate": 58, "peer_avg": 73, "deviation": "15 percentage points below Bombay HC peers", "percentile": 18, "label": "Among the most defendant-protective judges in Maharashtra"},
            "notable_cases": [
                {"name": "Suniel Shetty v. Netflix (2021)", "type": "IP / Copyright", "outcome": "Balanced copyright vs. free expression — widely cited"},
                {"name": "NDPS Bail Guidelines (2022)", "type": "Criminal / Bail", "outcome": "Established proportionality framework — reduced undertrial suffering"},
            ],
            "bio_summary": "Justice Patel was celebrated for precise prose and civil liberties rulings. Known as a 'judge's judge', he resigned in 2023 to return to practice. His bail jurisprudence in NDPS cases and LGBTQ rulings significantly advanced individual rights in the Bombay HC.",
        },

        {
            "id": "judge-005",
            "name": "Justice Hemant Gupta",
            "court": "Supreme Court of India",
            "jurisdiction": "Supreme Court",
            "location": "New Delhi",
            "years_on_bench": 22,
            "total_cases": 5234,
            "appointed_by": "Elevated to SC — Oct 2019 (Retired Oct 2022)",
            "education": "Chandigarh College of Law",
            "case_types": ["Criminal", "Constitutional", "Education", "Minority Rights"],
            "ruling_breakdown": {"prosecution_win_pct": 82, "defense_win_pct": 18, "appeals_reversed_pct": 28},
            "demographic_patterns": {
                "general_upper_caste": {"conviction_rate": 72, "avg_sentence_months": 24},
                "obc": {"conviction_rate": 80, "avg_sentence_months": 32},
                "sc_st": {"conviction_rate": 84, "avg_sentence_months": 38},
                "minority": {"conviction_rate": 87, "avg_sentence_months": 42},
            },
            "bias_score": 74,
            "bias_risk": "high",
            "bias_indicators": [
                "15% higher conviction rate for minority defendants vs upper caste",
                "18-month average sentencing disparity (minority vs. upper caste)",
                "Lone dissent in Karnataka Hijab case — would have upheld state ban",
                "28% reversal rate significantly above court average of 15%",
            ],
            "bias_breakdown": {
                "caste_religious": {"score": 72, "grade": "D", "label": "Caste / Religious Bias",
                    "data_points": [
                        {"metric": "SC/ST vs. General conviction gap", "value": "+12%", "benchmark": "Threshold: +5%", "status": "fail"},
                        {"metric": "Muslim vs. Hindu sentence disparity", "value": "+18 months avg", "benchmark": "Threshold: +4 months", "status": "fail"},
                        {"metric": "Minority bail denial uplift", "value": "+24%", "benchmark": "Threshold: +8%", "status": "fail"},
                    ], "verdict": "Statistically significant bias against religious minorities and SC/ST defendants. Constitutional scholars have noted the pattern in his minority-rights dissents."},
                "gender": {"score": 58, "grade": "C", "label": "Gender Bias",
                    "data_points": [
                        {"metric": "Female defendant conviction rate vs male", "value": "-3%", "benchmark": "Within range", "status": "pass"},
                        {"metric": "Female survivor outcome in DV cases", "value": "Favorable 52%", "benchmark": "National avg: 61%", "status": "warn"},
                        {"metric": "Gender-religion intersection — Muslim women", "value": "Favorable only 31%", "benchmark": "National avg: 61%", "status": "fail"},
                    ], "verdict": "Moderate gender bias, heavily compounded when religious minority identity intersects with gender."},
                "socioeconomic": {"score": 65, "grade": "D", "label": "Socioeconomic Bias",
                    "data_points": [
                        {"metric": "Corporate defendant conviction rate", "value": "38%", "benchmark": "National avg: 67%", "status": "fail"},
                        {"metric": "Legal aid vs. Senior Advocate outcome gap", "value": "+29%", "benchmark": "Threshold: +15%", "status": "fail"},
                    ], "verdict": "Clear economic class patterns — corporate and affluent defendants fare significantly better."},
                "recidivism": {"score": 80, "grade": "F", "label": "Recidivism Bias",
                    "data_points": [
                        {"metric": "Any prior record: sentence uplift", "value": "+54%", "benchmark": "Guideline: +15–25%", "status": "fail"},
                        {"metric": "Prior acquitted FIR used in sentencing", "value": "Yes, in 34% of cases", "benchmark": "Threshold: Never", "status": "fail"},
                    ], "verdict": "Extreme recidivism weighting — prior acquitted cases were used as aggravating factors, contrary to settled law."},
                "geographic": {"score": 68, "grade": "D", "label": "Geographic / Regional Bias",
                    "data_points": [
                        {"metric": "Minority-majority district defendant outcome", "value": "+19%", "benchmark": "Threshold: +5%", "status": "fail"},
                        {"metric": "NE India vs. mainland defendant gap", "value": "+11%", "benchmark": "Threshold: +6%", "status": "fail"},
                    ], "verdict": "Significant regional bias — defendants from minority-concentrated or northeastern regions faced consistently harder outcomes."},
            },
            "report_card": {"overall": "D", "caste_religious": "D", "gender": "C", "socioeconomic": "D", "recidivism": "F", "geographic": "D"},
            "comparable_cases": [
                {
                    "crime": "Karnataka Hijab Ban — Article 25 challenge (two identical petitions)",
                    "year": 2022,
                    "defendant_a": {"community": "Muslim (Hijab-wearing student)", "gender": "Female", "economic_class": "Middle Class", "counsel": "Senior Advocate", "outcome": "PETITION DISMISSED", "sentence": "Ban upheld (Gupta's lone dissent)", "bail_on_appeal": "N/A"},
                    "defendant_b": {"community": "Hindu (Religious symbol wearer)", "gender": "Female", "economic_class": "Middle Class", "counsel": "Senior Advocate", "outcome": "NOT ADJUDICATED", "sentence": "No restriction imposed historically", "bail_on_appeal": "N/A"},
                    "observation": "Only one religion's expression was subject to a ban. Justice Gupta's sole dissent would have enforced the Muslim-specific ban — no comparable Hindu religious expression was ever challenged.",
                    "bias_type": "caste_religious",
                },
                {
                    "crime": "UAPA Bail Application (two simultaneous applications, similar factual matrices)",
                    "year": 2021,
                    "defendant_a": {"community": "Muslim (Journalist)", "gender": "Male", "economic_class": "Working Press", "counsel": "HC Advocate", "outcome": "BAIL DENIED", "sentence": "Undertrial 18 months+", "bail_on_appeal": "Reversed by 3-judge bench"},
                    "defendant_b": {"community": "Upper Caste (accused in different state)", "gender": "Male", "economic_class": "Businessman", "counsel": "Senior Advocate", "outcome": "BAIL GRANTED", "sentence": "N/A", "bail_on_appeal": "N/A"},
                    "observation": "Both applications heard within 2 weeks. The Muslim journalist's bail was denied; later reversed by a higher bench. The businessman's bail was granted in the same month.",
                    "bias_type": "caste_religious",
                },
            ],
            "timeline": [
                {"year": 2019, "conviction_rate": 78, "avg_sentence_months": 36, "bail_denial_rate": 62, "notable": "First year on SC — immediately elevated conviction rates"},
                {"year": 2020, "conviction_rate": 81, "avg_sentence_months": 40, "bail_denial_rate": 71, "notable": "UAPA bail denials begin — Bhima Koregaon related"},
                {"year": 2021, "conviction_rate": 83, "avg_sentence_months": 42, "bail_denial_rate": 74, "notable": "Multiple UAPA bail denials — peak period"},
                {"year": 2022, "conviction_rate": 84, "avg_sentence_months": 43, "bail_denial_rate": 76, "notable": "Karnataka Hijab lone dissent — career-defining controversy"},
                {"year": 2022, "conviction_rate": 82, "avg_sentence_months": 41, "bail_denial_rate": 73, "notable": "Retired October 2022"},
            ],
            "temporal_patterns": {
                "day_of_week": [
                    {"day": "Mon", "conviction_rate": 87, "bail_denial_rate": 81},
                    {"day": "Tue", "conviction_rate": 84, "bail_denial_rate": 77},
                    {"day": "Wed", "conviction_rate": 82, "bail_denial_rate": 74},
                    {"day": "Thu", "conviction_rate": 83, "bail_denial_rate": 75},
                    {"day": "Fri", "conviction_rate": 79, "bail_denial_rate": 69},
                ],
                "time_of_day": [
                    {"slot": "9–11am", "bail_denial_rate": 82, "label": "Morning"},
                    {"slot": "11am–1pm", "bail_denial_rate": 88, "label": "Pre-Lunch"},
                    {"slot": "2–4pm", "bail_denial_rate": 74, "label": "Post-Lunch"},
                    {"slot": "4–6pm", "bail_denial_rate": 67, "label": "Late"},
                ],
                "election_year_effect": {"election_year_conviction_rate": 86, "normal_year_rate": 79, "difference": "+7%", "assessment": "Marked election-year spike. Cases with political dimensions saw sharply worse outcomes for defendants during 2019."},
                "media_effect": {"high_profile_rate": 89, "routine_rate": 77, "difference": "+12%", "assessment": "Strong media contagion effect — high-profile cases resulted in significantly harsher bail denial rates."},
                "monday_effect": "+8pp above weekly average — 'start of week severity' strongly present",
                "lunch_effect": "+14pp bail denial pre-lunch vs. post-lunch — among highest fatigue effects observed",
            },
            "outlier_score": {"score": 12, "direction": "above", "this_judge_conviction_rate": 82, "peer_avg": 70, "deviation": "12 percentage points above SC peer average", "percentile": 92, "label": "Top 8% most prosecution-friendly on the Supreme Court"},
            "notable_cases": [
                {"name": "Karnataka Hijab Case (2022)", "type": "Constitutional / Education", "outcome": "Lone dissent — would have upheld discriminatory ban on hijab in schools"},
                {"name": "UAPA Bail — Multiple (2020-22)", "type": "Criminal / Constitutional", "outcome": "Series of bail denials — several subsequently overturned by higher benches"},
            ],
            "bio_summary": "Justice Gupta's tenure produced a consistent pattern of minority-adverse outcomes. His lone dissent in the Hijab case is among the most cited examples of judicial religious bias in recent SC history. His 28% reversal rate and temporal patterns suggest both institutional bias and decision fatigue.",
        },

        {
            "id": "judge-006",
            "name": "Justice Sudhanshu Dhulia",
            "court": "Supreme Court of India",
            "jurisdiction": "Supreme Court",
            "location": "New Delhi",
            "years_on_bench": 18,
            "total_cases": 3156,
            "appointed_by": "Elevated to SC — May 2022",
            "education": "Allahabad University School of Law",
            "case_types": ["Constitutional", "Criminal", "Minority Rights", "Bail", "Labour"],
            "ruling_breakdown": {"prosecution_win_pct": 60, "defense_win_pct": 40, "appeals_reversed_pct": 9},
            "demographic_patterns": {
                "general_upper_caste": {"conviction_rate": 61, "avg_sentence_months": 22},
                "obc": {"conviction_rate": 60, "avg_sentence_months": 22},
                "sc_st": {"conviction_rate": 62, "avg_sentence_months": 23},
                "minority": {"conviction_rate": 59, "avg_sentence_months": 21},
            },
            "bias_score": 25,
            "bias_risk": "low",
            "bias_indicators": [
                "3% or less variance in outcomes across all demographic groups",
                "Wrote the minority opinion allowing hijab — protecting minority rights",
                "Strongly advocates for bail — low pretrial detention rates",
            ],
            "bias_breakdown": {
                "caste_religious": {"score": 20, "grade": "A", "label": "Caste / Religious Bias",
                    "data_points": [
                        {"metric": "SC/ST vs. General conviction gap", "value": "+1%", "benchmark": "Threshold: +5%", "status": "pass"},
                        {"metric": "Minority sentence: slightly favoured", "value": "-1 month", "benchmark": "Threshold: +4 months", "status": "pass"},
                    ], "verdict": "Exemplary. Minority defendants marginally better off — consistent with his stated commitment to equal protection."},
                "gender": {"score": 22, "grade": "A", "label": "Gender Bias",
                    "data_points": [
                        {"metric": "Male vs. female conviction gap", "value": "+3%", "benchmark": "Threshold: +8%", "status": "pass"},
                        {"metric": "Domestic violence survivor outcomes", "value": "Favorable 68%", "benchmark": "National avg: 61%", "status": "pass"},
                    ], "verdict": "Strong gender equity. Above-average protective outcomes for domestic violence survivors."},
                "socioeconomic": {"score": 30, "grade": "B", "label": "Socioeconomic Bias",
                    "data_points": [
                        {"metric": "Bail: affluent vs. legal aid gap", "value": "+7% grant gap", "benchmark": "Threshold: +15%", "status": "pass"},
                        {"metric": "Legal aid client outcomes", "value": "-9% below private counsel", "benchmark": "Threshold: -15%", "status": "pass"},
                    ], "verdict": "Modest socioeconomic gradient — primarily reflects systemic inequality, not personal bias."},
                "recidivism": {"score": 38, "grade": "B", "label": "Recidivism Bias",
                    "data_points": [
                        {"metric": "Repeat offender sentence uplift", "value": "+22%", "benchmark": "Guideline: +15–25%", "status": "pass"},
                        {"metric": "First offender diversion rate", "value": "24%", "benchmark": "National avg: 18%", "status": "pass"},
                    ], "verdict": "Balanced recidivism approach. Proportionate uplift for prior records, above-average diversion for first offenders."},
                "geographic": {"score": 18, "grade": "A", "label": "Geographic / Regional Bias",
                    "data_points": [
                        {"metric": "Urban vs. rural defendant gap", "value": "+2%", "benchmark": "Threshold: +6%", "status": "pass"},
                    ], "verdict": "No geographic bias pattern detected."},
            },
            "report_card": {"overall": "A", "caste_religious": "A", "gender": "A", "socioeconomic": "B", "recidivism": "B", "geographic": "A"},
            "comparable_cases": [
                {
                    "crime": "Karnataka Hijab Ban — Article 25 challenge (same case, differing benches)",
                    "year": 2022,
                    "defendant_a": {"community": "Muslim (Student)", "gender": "Female", "economic_class": "Middle Class", "counsel": "Senior Advocate", "outcome": "PROTECTED", "sentence": "Hijab allowed — Dhulia's dissent", "bail_on_appeal": "N/A"},
                    "defendant_b": {"community": "Same Muslim students (Gupta bench)", "gender": "Female", "economic_class": "Middle Class", "counsel": "Same Advocate", "outcome": "NOT PROTECTED", "sentence": "Ban upheld — Gupta's dissent reversed the outcome", "bail_on_appeal": "N/A"},
                    "observation": "Same case. Two dissenting opinions. Dhulia protected the right; Gupta would have enforced the ban. A direct judicial contrast in the same matter.",
                    "bias_type": "caste_religious",
                },
            ],
            "timeline": [
                {"year": 2018, "conviction_rate": 58, "avg_sentence_months": 20, "bail_denial_rate": 36, "notable": "High Court — strong bail jurisprudence begins"},
                {"year": 2019, "conviction_rate": 59, "avg_sentence_months": 21, "bail_denial_rate": 37, "notable": "Election year — minimal effect"},
                {"year": 2020, "conviction_rate": 60, "avg_sentence_months": 22, "bail_denial_rate": 38, "notable": "COVID bail orders — granted bail in most cases"},
                {"year": 2021, "conviction_rate": 61, "avg_sentence_months": 22, "bail_denial_rate": 38, "notable": "Elevated to SC — May 2022"},
                {"year": 2022, "conviction_rate": 60, "avg_sentence_months": 22, "bail_denial_rate": 37, "notable": "Karnataka Hijab dissent — protecting minority rights"},
                {"year": 2023, "conviction_rate": 61, "avg_sentence_months": 23, "bail_denial_rate": 39, "notable": "NDPS proportionality framework established"},
                {"year": 2024, "conviction_rate": 61, "avg_sentence_months": 22, "bail_denial_rate": 38, "notable": "Continues consistent pattern on SC"},
            ],
            "temporal_patterns": {
                "day_of_week": [
                    {"day": "Mon", "conviction_rate": 63, "bail_denial_rate": 42},
                    {"day": "Tue", "conviction_rate": 61, "bail_denial_rate": 40},
                    {"day": "Wed", "conviction_rate": 60, "bail_denial_rate": 38},
                    {"day": "Thu", "conviction_rate": 61, "bail_denial_rate": 38},
                    {"day": "Fri", "conviction_rate": 59, "bail_denial_rate": 35},
                ],
                "time_of_day": [
                    {"slot": "9–11am", "bail_denial_rate": 40, "label": "Morning"},
                    {"slot": "11am–1pm", "bail_denial_rate": 38, "label": "Pre-Lunch"},
                    {"slot": "2–4pm", "bail_denial_rate": 38, "label": "Post-Lunch"},
                    {"slot": "4–6pm", "bail_denial_rate": 35, "label": "Late"},
                ],
                "election_year_effect": {"election_year_conviction_rate": 60, "normal_year_rate": 61, "difference": "-1%", "assessment": "Slight decrease during election years — no detectable political pressure effect"},
                "media_effect": {"high_profile_rate": 62, "routine_rate": 60, "difference": "+2%", "assessment": "Negligible media effect — among the most media-independent patterns on the court"},
                "monday_effect": "+2pp above weekly average — very mild",
                "lunch_effect": "-2pp post-lunch — minimal",
            },
            "outlier_score": {"score": -10, "direction": "below", "this_judge_conviction_rate": 60, "peer_avg": 70, "deviation": "10 percentage points below SC peer average", "percentile": 22, "label": "Among the more defendant-protective voices on the current Supreme Court"},
            "notable_cases": [
                {"name": "Karnataka Hijab Case (2022)", "type": "Constitutional / Education", "outcome": "Dissent — allowed hijab; protected religious expression under Article 25"},
                {"name": "NDPS Bail Framework (2023)", "type": "Criminal / Bail", "outcome": "Proportionality framework for bail — reduced undertrial prisoners"},
            ],
            "bio_summary": "Justice Dhulia is regarded as one of the most rights-protective voices on the current Supreme Court. His dissent in the Hijab case has been widely praised for upholding constitutional pluralism. His bail jurisprudence has directly reduced undertrial suffering.",
        },
    ]


def get_laws_data():
    return [
        {"id": "law-001", "code": "IPC § 302", "title": "Punishment for Murder", "category": "Criminal", "applicable_case_types": ["criminal", "murder", "homicide"], "summary": "Whoever commits murder shall be punished with death, or imprisonment for life, and shall also be liable to fine. Landmark: Bachan Singh v. State of Punjab (1980) — 'rarest of rare' doctrine for death penalty.", "max_penalty": "Death penalty or Life imprisonment + Fine"},
        {"id": "law-002", "code": "IPC § 376", "title": "Punishment for Rape / Sexual Assault", "category": "Criminal", "applicable_case_types": ["criminal", "sexual assault", "rape", "domestic violence"], "summary": "Penalizes rape with minimum 10 years rigorous imprisonment, extendable to life or death. Post-Nirbhaya (2012) reforms enhanced minimum punishment.", "max_penalty": "10 years to life (death in aggravated cases)"},
        {"id": "law-003", "code": "IPC § 420", "title": "Cheating and Dishonestly Inducing Delivery of Property", "category": "Criminal", "applicable_case_types": ["criminal", "fraud", "corporate", "cheating"], "summary": "Criminalizes cheating resulting in delivery of property or alteration of valuable security. Widely used in corporate fraud and real estate cases.", "max_penalty": "7 years imprisonment + Fine"},
        {"id": "law-004", "code": "IPC § 498A", "title": "Husband or Relative Subjecting Woman to Cruelty", "category": "Criminal", "applicable_case_types": ["domestic violence", "criminal", "family"], "summary": "Makes cruelty by husband or relatives a cognizable, non-bailable, non-compoundable offence. Arnesh Kumar (2014) SC guidelines limit automatic arrest.", "max_penalty": "3 years imprisonment + Fine"},
        {"id": "law-005", "code": "NDPS Act § 21", "title": "Punishment for Contraband Narcotic Drugs", "category": "Criminal", "applicable_case_types": ["criminal", "drug", "narcotics", "ndps"], "summary": "Penalizes possession, transport, sale of narcotic drugs. Distinguishes small (1 yr), intermediate (10 yrs), and commercial (10–20 yrs) quantities. Section 37 restricts bail.", "max_penalty": "10–20 years RI + Fine (commercial quantity)"},
        {"id": "law-006", "code": "Constitution — Article 21", "title": "Right to Life and Personal Liberty", "category": "Constitutional", "applicable_case_types": ["constitutional", "criminal", "civil rights", "bail"], "summary": "No person shall be deprived of life or personal liberty except according to procedure established by law. Expanded to include privacy (Puttaswamy, 2017), health, livelihood, and speedy trial.", "max_penalty": "N/A — Fundamental Right"},
        {"id": "law-007", "code": "Constitution — Article 14", "title": "Equality Before Law", "category": "Constitutional", "applicable_case_types": ["constitutional", "discrimination", "civil rights"], "summary": "Guarantees equality before law and equal protection of laws. Prohibits arbitrary state action. Twin tests: intelligible differentia and rational nexus.", "max_penalty": "N/A — Fundamental Right"},
        {"id": "law-008", "code": "Constitution — Article 22", "title": "Protection Against Arbitrary Arrest and Detention", "category": "Constitutional", "applicable_case_types": ["criminal", "constitutional", "bail", "detention"], "summary": "Right to be informed of grounds of arrest, right to legal representation, and right to be produced before magistrate within 24 hours.", "max_penalty": "N/A — Fundamental Right"},
        {"id": "law-009", "code": "CrPC § 438", "title": "Anticipatory Bail", "category": "Procedural", "applicable_case_types": ["criminal", "bail", "procedural"], "summary": "Allows anticipatory bail application before arrest. HC and Sessions Court have concurrent jurisdiction. Conditions governed by Sushila Aggarwal (2020).", "max_penalty": "N/A — Procedural Relief"},
        {"id": "law-010", "code": "CrPC § 482", "title": "Inherent Powers of High Court", "category": "Procedural", "applicable_case_types": ["criminal", "constitutional", "procedural"], "summary": "Preserves HC inherent powers to prevent abuse of process or secure justice. Used to quash FIRs, stay proceedings, and enforce rights when other remedies fail.", "max_penalty": "N/A — Procedural Power"},
        {"id": "law-011", "code": "POCSO Act § 4", "title": "Punishment for Penetrative Sexual Assault on Minor", "category": "Criminal", "applicable_case_types": ["criminal", "child abuse", "pocso", "sexual assault"], "summary": "POCSO Act 2012 — minimum 20 years RI for penetrative sexual assault on child (under 18). Presumption of guilt under Section 29 reverses burden of proof.", "max_penalty": "20 years to life imprisonment or death"},
        {"id": "law-012", "code": "Prevention of Corruption Act § 7", "title": "Offence Relating to Public Servant Being Bribed", "category": "Criminal", "applicable_case_types": ["criminal", "corruption", "bribery"], "summary": "Penalizes public servants accepting gratification beyond legal remuneration. 2018 amendment also penalizes bribe-giver. Sanction required before prosecution.", "max_penalty": "3–7 years + Fine"},
        {"id": "law-013", "code": "DV Act § 3", "title": "Definition of Domestic Violence", "category": "Civil/Criminal", "applicable_case_types": ["domestic violence", "family", "civil rights"], "summary": "Provides civil remedies (protection orders, residence orders, monetary relief) for domestic violence. Covers physical, sexual, verbal, emotional, economic abuse. Applies to live-in relationships.", "max_penalty": "1 year / Rs. 20,000 fine (breach of protection order)"},
        {"id": "law-014", "code": "UAPA § 15", "title": "Terrorist Act", "category": "Criminal", "applicable_case_types": ["criminal", "terrorism", "uapa", "national security"], "summary": "Defines and penalizes terrorist acts, organization membership, and support. Section 43D creates near-absolute bar on bail — upheld in Zahoor Ahmed Shah Watali (2019).", "max_penalty": "Death penalty or Life imprisonment"},
        {"id": "law-015", "code": "IT Act § 66", "title": "Computer Related Offences", "category": "Criminal", "applicable_case_types": ["criminal", "cyber", "technology", "fraud"], "summary": "Penalizes unauthorized computer access and data theft. Note: Section 66A (online speech) struck down in Shreya Singhal v. UoI (2015) — violation of Article 19(1)(a).", "max_penalty": "3 years + Fine up to Rs. 5 lakh"},
    ]
